# Generated by Django 5.2.10 on 2026-02-18 13:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_carro_motoristas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="montadora",
            field=models.ForeignKey(
                default=1,
                on_delete=models.SET(core.models.set_default_montadora),
                to="core.montadora",
            ),
        ),
    ]
