# Generated by Django 5.2.10 on 2026-02-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Equipe",
            new_name="Funcionario",
        ),
    ]
