# Generated by Django 5.2.10 on 2026-02-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="features",
            name="icone",
            field=models.CharField(
                choices=[
                    ("lni-cog", "Engrenagem"),
                    ("lni-stats-up", "Gráfico"),
                    ("lni-leaf", "Folha"),
                    ("lni-layers", "Design"),
                    ("lni-laptop-phone", "Computador e Celular"),
                    ("lni-rocket", "Foguete"),
                ],
                max_length=16,
                verbose_name="Ícone",
            ),
        ),
    ]
